version: '3.4'

services:
  postgres:
    container_name: hotel-book-pg
    image: postgres:15.2-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${HB_PG_USER}
      POSTGRES_DB: ${HB_PG_DB}
      POSTGRES_PASSWORD: ${HB_PG_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - ${HB_PG_PORT}:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata

  server:
    container_name: hotel-book-server
    image: ghcr.io/lev3fon/yasnagorka-server:latest
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - ${SERVER_PORT}:3030
    volumes:
      - ./uploads:/app/uploads:rw
